### ISSUE TITLE
Host kann auf jede Party   zugreifen

### ISSUE THREAD

**Issue by AlexBoehner** [AlexBoehner/TeamPlayServer#1]
Der Host kann mom. noch auf jede Party zugreifen. Es wird nicht partyid mit hostid kontrolliert.

Vllt. Bei Authentificierung lösen?? || Prüfungen in Ressourcen

**Comment by mdinkelberg** [comment]
Du gehst also davon aus, dass der Host die URL selbst manipuliert, oder? Weil wenn er das nicht tut, sondern sich nur über die Links bewegt, kommt er nur auf seine eigenen Partys, wenn ich das richtig sehe. In PartysResource werden die Partys über den jeweiligen Host abgerufen.
